import { createClient } from "npm:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-hub-signature-256","Content-Type":"application/json"};const hmacHex=async(secret:string,body:string)=>{const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(body));return Array.from(new Uint8Array(sig)).map(x=>x.toString(16).padStart(2,"0")).join("")};
const safeEqual=(a:string,b:string)=>{if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:cors});
Deno.serve(async(req)=>{try{if(req.method==="GET"){const u=new URL(req.url),mode=u.searchParams.get("hub.mode"),token=u.searchParams.get("hub.verify_token"),challenge=u.searchParams.get("hub.challenge");if(mode==="subscribe"&&token&&challenge){const sk=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")??"{}"),url=Deno.env.get("SUPABASE_URL"),secret=sk.default;if(!url||!secret)return new Response("configuration error",{status:500});const db=createClient(url,secret),{data:valid,error}=await db.rpc("verify_whatsapp_webhook_token_internal",{p_verify_token:token});if(error)return new Response("verification error",{status:500});if(valid===true||Array.isArray(valid)&&valid[0]===true)return new Response(challenge,{status:200});} return new Response("forbidden",{status:403})}
const raw=await req.text(),sk=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")??"{}"),url=Deno.env.get("SUPABASE_URL"),secret=sk.default;if(!url||!secret)return json({error:"Function configuration is incomplete"},500);const ad=createClient(url,secret);
const signature=(req.headers.get("x-hub-signature-256")||"").trim();
if(!/^sha256=[0-9a-f]{64}$/i.test(signature))return json({error:"Missing or invalid webhook signature"},401);
const{data:appSecrets,error:ase}=await ad.rpc("get_whatsapp_app_secrets_internal");if(ase)return json({error:"Webhook verification configuration error"},500);
const provided=signature.slice(7).toLowerCase();
let verified=false;
for(const row of (Array.isArray(appSecrets)?appSecrets:[])){if(row?.meta_app_secret){const expected=(await hmacHex(row.meta_app_secret,raw)).toLowerCase();if(safeEqual(expected,provided)){verified=true;break}}}
if(!verified)return json({error:"Invalid webhook signature"},401);
let body:any;try{body=JSON.parse(raw)}catch{return json({error:"Invalid JSON"},400)}
for(const entry of body.entry??[])for(const ch of entry.changes??[])for(const s of ch.value?.statuses??[]){const state=s.status==="read"?"read":s.status==="delivered"?"delivered":s.status==="sent"?"sent":s.status==="failed"?"failed":"pending";const errorMessage=s.status==="failed"?JSON.stringify(s.errors??[]):null;await ad.from("notification_logs").update({delivery_status:state,status:state==="failed"?"failed":"sent",error_message:errorMessage}).eq("provider_message_id",s.id);const{data:logs}=await ad.from("notification_logs").select("notification_id").eq("provider_message_id",s.id);for(const l of logs??[])await ad.from("notifications").update({status:state==="failed"?"failed":"sent",delivery_status:state,error_message:errorMessage}).eq("id",l.notification_id)}
return json({ok:true})}catch(e){return json({error:e instanceof Error?e.message:"Unexpected error"},500)}});