import { createClient } from "npm:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type, x-worker-secret","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:cors});
const val=(k:string,n:any)=>({member_name:n.members?.name,member_id:n.members?.member_id,gym_name:n.gyms?.name,package_name:n.memberships?.membership_packages?.name,start_date:n.memberships?.start_date,expiry_date:n.memberships?.end_date,gym_phone:n.gyms?.phone,gym_whatsapp:n.gyms?.whatsapp})[k]??"";
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{
if(req.headers.get("x-worker-secret")!==Deno.env.get("WHATSAPP_WORKER_SECRET"))return json({error:"Unauthorized"},401);
const sk=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")??"{}"),url=Deno.env.get("SUPABASE_URL"),service=sk.default,access=Deno.env.get("WHATSAPP_ACCESS_TOKEN"),numberId=Deno.env.get("WHATSAPP_PHONE_NUMBER_ID"),version=Deno.env.get("WHATSAPP_API_VERSION");if(!url||!service||!access||!numberId||!version)return json({error:"WhatsApp worker is not configured"},500);
const db=createClient(url,service),{data:rows}=await db.from("notifications").select("id,message_body,retry_count,notification_type,gym_id,members(name,member_id,phone),gyms(name,phone,whatsapp),memberships(start_date,end_date,membership_packages(name))").eq("channel","whatsapp").in("status",["queued","failed"]).lt("retry_count",3).order("scheduled_at").limit(50);
let sent=0,failed=0;for(const n of rows??[]){if(!n.members?.phone)continue;const{data:t}=await db.from("notification_templates").select("provider_template_name,provider_template_language,provider_template_variables").eq("gym_id",n.gym_id).eq("notification_type",n.notification_type).eq("channel","whatsapp").eq("enabled",true).maybeSingle();let msg:any={messaging_product:"whatsapp",to:n.members.phone.replace(/\D/g,"")};if(t?.provider_template_name){msg.type="template";msg.template={name:t.provider_template_name,language:{code:t.provider_template_language||"en_US"}};const vars=t.provider_template_variables??[];if(vars.length)msg.template.components=[{type:"body",parameters:vars.map((k:string)=>({type:"text",text:String(val(k,n))}))}]}else{msg.type="text";msg.text={preview_url:false,body:n.message_body??"Your gym membership needs attention."}}const resp=await fetch("https://graph.facebook.com/"+version+"/"+numberId+"/messages",{method:"POST",headers:{Authorization:"Bearer "+access,"Content-Type":"application/json"},body:JSON.stringify(msg)}),result=await resp.json(),pid=result?.messages?.[0]?.id??null;await db.from("notification_logs").insert({notification_id:n.id,status:resp.ok?"sent":"failed",delivery_status:resp.ok?"sent":"failed",provider_message_id:pid,error_message:resp.ok?null:JSON.stringify(result)});await db.from("notifications").update({status:resp.ok?"sent":"failed",delivery_status:resp.ok?"sent":"failed",sent_at:resp.ok?new Date().toISOString():null,error_message:resp.ok?null:JSON.stringify(result),retry_count:(n.retry_count??0)+(resp.ok?0:1)}).eq("id",n.id);if(resp.ok)sent++;else failed}
return json({ok:true,processed:sent+failed,sent,failed})}catch(e){return json({error:e instanceof Error?e.message:"Unexpected error"},500)}});