import React,{useEffect,useMemo,useState}from'react';
import{Area,AreaChart,CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis}from'recharts';
import{BarChart3,Check,CircleDollarSign,Clock3,FileBarChart,RefreshCw,UserPlus,Users}from'lucide-react';
import{loadAnalytics,loadAttention,money}from'../data';
import{Empty,Metric,Panel,PageHeader,Quick,StatusTag,Summary,initials}from'../components/ui';

function range(p:string){const d=new Date(),today=d.toISOString().slice(0,10);if(p==='today')return{from:today,to:today};if(p==='week'){const x=new Date(d);x.setDate(d.getDate()-d.getDay());return{from:x.toISOString().slice(0,10),to:today}}if(p==='last')return{from:new Date(d.getFullYear(),d.getMonth()-1,1).toISOString().slice(0,10),to:new Date(d.getFullYear(),d.getMonth(),0).toISOString().slice(0,10)};if(p==='year')return{from:d.getFullYear()+'-01-01',to:today};return{from:d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-01',to:today}}
function trend(a:any[]){return(a||[]).map(x=>({date:new Date(x.date+'T00:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short'}),value:Number(x.value||0)}))}
export function Dashboard({gymId,onNavigate,onOpen,refresh}:{gymId:string;onNavigate:(s:any)=>void;onOpen:(t:string)=>void;refresh:number}){
 const[preset,setPreset]=useState('month'),[data,setData]=useState<any>(),[attention,setAttention]=useState<any>(),[busy,setBusy]=useState(true),r=useMemo(()=>range(preset),[preset]);
 useEffect(()=>{let live=true;setBusy(true);Promise.all([loadAnalytics(gymId,r.from,r.to),loadAttention(gymId)]).then(([a,b])=>{if(live){setData(a);setAttention(b)}}).catch(()=>{}).finally(()=>live&&setBusy(false));return()=>{live=false}},[gymId,r.from,r.to,refresh]);
 return <><PageHeader title="Good morning 👋" subtitle="Live business command center." action={<div className="toolbar-actions"><select className="compact-select" value={preset} onChange={e=>setPreset(e.target.value)}><option value="today">Today</option><option value="week">This Week</option><option value="month">This Month</option><option value="last">Last Month</option><option value="year">This Year</option></select><button className="icon-button" onClick={()=>window.dispatchEvent(new Event('gym:refresh'))}><RefreshCw size={18}/></button></div>}/>
 <div className="kpi-grid">{[
 ['Money collected',money(data?.revenue||0),'Successful payments'],['New joiners',data?.new_members||0,'Selected period'],['Renewals',data?.renewals||0,'Selected period'],
 ['Did not renew',data?.did_not_renew||0,'After grace period'],['Renewal rate',(data?.renewal_rate||0)+'%','Eligible vs renewed'],['Active members',data?.active||0,'Current'],['Expiring soon',data?.expiring_soon||0,'Next 10 days'],['Outstanding',money(data?.outstanding||0),'Current balance']
 ].map(([a,b,c],i)=><Metric key={String(a)} title={String(a)} value={busy?'—':b as any} detail={String(c)} warning={i===7}/>)}</div>
 <div className="quick-section"><div className="section-title"><h2>Quick actions</h2></div><div className="quick-grid"><Quick label="Add member" icon={UserPlus} onClick={()=>onOpen('add-member')}/><Quick label="Renew membership" icon={RefreshCw} onClick={()=>onNavigate('members')}/><Quick label="Record payment" icon={CircleDollarSign} onClick={()=>onNavigate('payments')}/><Quick label="Attendance" icon={Check} onClick={()=>onNavigate('attendance')}/><Quick label="Analytics" icon={BarChart3} onClick={()=>onNavigate('analytics')}/><Quick label="Reports" icon={FileBarChart} onClick={()=>onNavigate('reports')}/></div></div>
 <div className="dashboard-grid"><Panel title="Revenue trend"><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend(data?.revenue_trend)}><defs><linearGradient id="liveRevenue" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopOpacity=".25"/><stop offset="100%" stopOpacity="0"/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#272730"/><XAxis dataKey="date" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip/><Area type="monotone" dataKey="value" stroke="#a38bff" fill="url(#liveRevenue)" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></Panel>
 <Panel title="Today’s pulse" extra={<Users size={18}/>}>
 <div className="summary-strip"><Summary title="Check-ins" value={data?.total_members?String(data?.today_attendance||0):'0'}/><Summary title="Active" value={data?.active||0}/><Summary title="Expiring" value={data?.expiring_soon||0}/><Summary title="Pending renewals" value={data?.pending_renewal||0}/></div>
 </Panel></div>
 <div className="dashboard-grid"><Panel title="Expiring soon" extra={<button className="text-button" onClick={()=>onNavigate('reports')}>View report</button>}>{(attention?.expiring||[]).map((m:any)=><button className="attention-row" key={m.id} onClick={()=>onNavigate('members')}><div className="avatar">{initials(m.name)}</div><div><b>{m.name}</b><span>#{m.member_id} · {m.end_date}</span></div><StatusTag value={m.membership_status||''}/></button>)}{!busy&&!attention?.expiring?.length&&<Empty title="No memberships expiring" text="You're clear for the current window."/>}</Panel>
 <Panel title="Outstanding payments" extra={<button className="text-button" onClick={()=>onNavigate('reports')}>View report</button>}>{(attention?.outstanding||[]).map((x:any)=><div className="attention-row" key={x.member_uuid}><div className="avatar"><CircleDollarSign size={17}/></div><div><b>{x.name}</b><span>#{x.member_id}</span></div><strong>{money(Number(x.balance||0))}</strong></div>)}{!busy&&!attention?.outstanding?.length&&<Empty title="No outstanding payments" text="All current balances are settled."/>}</Panel></div>
 <Panel title="Business answers" extra={<Clock3 size={17}/>}><div className="summary-strip"><Summary title="Average membership" value={money(data?.avg_membership_value||0)}/><Summary title="Average payment" value={money(data?.avg_payment||0)}/><Summary title="Avg revenue/member" value={money(data?.avg_revenue_per_member||0)}/><Summary title="Expired / grace" value={data?.expired||0}/></div></Panel></>
}