import React,{useEffect,useMemo,useState}from'react';
import{Edit3,Phone,Plus,RefreshCw}from'lucide-react';
import{loadLeads,loadPackages,loadStaff,saveLead,localToday}from'../data';
import type{Package,Staff}from'../data';
import{DataTable,Empty,Field,Metric,Panel,PageHeader,Sheet,StatusTag,humanError}from'../components/ui';

const STATUSES=['new','contacted','trial','won','lost'];
const SOURCES=['walk_in','phone','whatsapp','instagram','facebook','website','referral','other'];

export function Leads({gymId,refresh}:{gymId:string;refresh:number}){
 const[status,setStatus]=useState('all'),[q,setQ]=useState(''),[rows,setRows]=useState<any[]>([]),[packages,setPackages]=useState<Package[]>([]),[staff,setStaff]=useState<Staff[]>([]),[editing,setEditing]=useState<any|null>(null),[error,setError]=useState('');
 const load=()=>Promise.all([loadLeads(gymId,{status,q}),loadPackages(gymId,false),loadStaff(gymId)]).then(([a,p,s])=>{setRows(a);setPackages(p);setStaff(s);setError('')}).catch((x:any)=>setError(humanError(x)));
 useEffect(()=>{load()},[gymId,status,q,refresh]);
 const due=rows.filter(x=>x.follow_up_date&&x.follow_up_date<=localToday()&&!['won','lost'].includes(x.status)).length;
 const counts=useMemo(()=>Object.fromEntries(STATUSES.map(s=>[s,rows.filter(x=>x.status===s).length])),[rows]);
 return <><PageHeader title="Leads & CRM" subtitle="Capture prospects, assign follow-ups and track the sales pipeline." action={<div className="toolbar-actions"><button className="icon-button" onClick={load} title="Refresh"><RefreshCw size={17}/></button><button className="primary" onClick={()=>setEditing({id:null,name:'',phone:'',email:'',source:'walk_in',status:'new',interested_package_id:'',assigned_to:'',follow_up_date:localToday(),notes:'',lost_reason:''})}><Plus size={16}/> Add lead</button></div>}/>{error&&<div className="error-banner">{error}</div>}<div className="kpi-grid">{[['New',counts.new],['Contacted',counts.contacted],['Trials',counts.trial],['Won',counts.won]].map(x=><Metric key={String(x[0])} title={String(x[0])} value={x[1]}/>)}</div><Panel title="Pipeline" extra={<span className={due?'warning':''}>{due} follow-ups due</span>}><div className="filters-row"><input placeholder="Search name or phone" value={q} onChange={e=>setQ(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All stages</option>{STATUSES.map(x=><option key={x}>{x}</option>)}</select></div>{!rows.length?<Empty title="No leads" text="Add your first prospect to start tracking enquiries."/>:<DataTable rows={rows.map((x:any)=>({Name:x.name,Phone:x.phone||'—',Source:x.source,Stage:x.status,Package:x.package_name||'—',FollowUp:x.follow_up_date||'—',Assigned:x.assigned_name||'—'}))} actions={(x:any)=>{const r=rows.find((a:any)=>a.name===x.Name&&String(a.phone||'')===String(x.Phone==='—'?'':x.Phone));return <div className="row-actions">{r?.phone&&<a className="secondary small" href={'tel:'+r.phone}><Phone size={13}/> Call</a>}{r&&<button className="icon-button mini" title="Edit" onClick={()=>setEditing(r)}><Edit3 size={13}/></button>}</div>}}/>}</Panel>{editing&&<LeadEditor gymId={gymId} initial={editing} packages={packages} staff={staff} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);load()}}/>}</>
}
function LeadEditor({gymId,initial,packages,staff,onClose,onSaved}:{gymId:string;initial:any;packages:Package[];staff:Staff[];onClose:()=>void;onSaved:()=>void}){
 const[f,setF]=useState(initial),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <Sheet title={f.id?'Edit lead':'Add lead'} onClose={onClose}><form className="form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await saveLead({gymId,id:f.id,name:f.name,phone:f.phone,email:f.email,source:f.source,status:f.status,packageId:f.interested_package_id||null,assignedTo:f.assigned_to||null,followUpDate:f.follow_up_date||null,notes:f.notes,lostReason:f.lost_reason});onSaved()}catch(x:any){setError(humanError(x))}finally{setBusy(false)}}}><div className="form-grid"><Field label="Name"><input required minLength={2} value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field label="Phone"><input value={f.phone||''} onChange={e=>setF({...f,phone:e.target.value})}/></Field><Field label="Email"><input type="email" value={f.email||''} onChange={e=>setF({...f,email:e.target.value})}/></Field><Field label="Source"><select value={f.source} onChange={e=>setF({...f,source:e.target.value})}>{SOURCES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Stage"><select value={f.status} onChange={e=>setF({...f,status:e.target.value})}>{STATUSES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Interested package"><select value={f.interested_package_id||''} onChange={e=>setF({...f,interested_package_id:e.target.value})}><option value="">Not selected</option>{packages.map(p=><option key={p.id} value={p.id}>{p.name} · {p.price}</option>)}</select></Field><Field label="Assigned to"><select value={f.assigned_to||''} onChange={e=>setF({...f,assigned_to:e.target.value})}><option value="">Unassigned</option>{staff.filter(s=>s.status==='active').map(s=><option key={s.id} value={s.id}>{s.name} · {s.role}</option>)}</select></Field><Field label="Follow-up date"><input type="date" value={f.follow_up_date||''} onChange={e=>setF({...f,follow_up_date:e.target.value})}/></Field></div><Field label="Notes"><textarea value={f.notes||''} onChange={e=>setF({...f,notes:e.target.value})}/></Field>{f.status==='lost'&&<Field label="Lost reason"><input value={f.lost_reason||''} onChange={e=>setF({...f,lost_reason:e.target.value})}/></Field>}{error&&<div className="error-inline">{error}</div>}<button className="primary full" disabled={busy}>{busy?'Saving…':'Save lead'}</button></form></Sheet>
}
