import React,{useEffect,useState}from'react';
import{CheckCircle2,MessageCircle,Plug,RefreshCw,Send,Trash2,AlertCircle}from'lucide-react';
import{loadMembers,loadNotificationLogs,loadNotifications,loadWhatsappConnection,queueNotification,saveWhatsappConnection,disconnectWhatsapp}from'../data';
import type{Member,Notification}from'../data';
import{DataTable,Empty,Field,Panel,PageHeader,Sheet,humanError}from'../components/ui';

export function WhatsApp({gymId,refresh,isAdmin}:{gymId:string;refresh:number;isAdmin:boolean}){
 const[connection,setConnection]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saved,setSaved]=useState(''),[sending,setSending]=useState<string|null>(null),[tab,setTab]=useState<'connection'|'messages'>('connection'),[notifications,setNotifications]=useState<Notification[]>([]),[logs,setLogs]=useState<any[]>([]),[logsRefresh,setLogsRefresh]=useState(0),[compose,setCompose]=useState(false);
 const load=async()=>{setLoading(true);try{const x=await loadWhatsappConnection(gymId);setConnection(Array.isArray(x)?x[0]:x);setError('')}catch(e:any){setError(humanError(e))}finally{setLoading(false)}};
 const loadMessages=async()=>{try{const[n,l]=await Promise.all([loadNotifications(gymId,0,100),loadNotificationLogs(gymId,0,100)]);setNotifications(n.rows.filter((x:any)=>x.channel==='whatsapp'));setLogs(l.rows)}catch(e:any){setError(humanError(e))}};
 useEffect(()=>{load()},[gymId,refresh]);useEffect(()=>{if(tab==='messages')loadMessages()},[tab,gymId,refresh,logsRefresh]);
 if(!isAdmin)return <><PageHeader title="WhatsApp" subtitle="WhatsApp connection and message delivery."/><Empty title="Admin access required" text="Only an admin can configure the gym's WhatsApp connection."/></>;
 return <><PageHeader title="WhatsApp" subtitle="Connect your gym's WhatsApp Business account, send custom messages and monitor delivery." action={<button className="icon-button" onClick={()=>{load();loadMessages()}}><RefreshCw size={17}/></button>}/>{error&&<div className="error-banner">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}{saved&&<div className="success-banner">{saved}</div>}<div className="settings-tabs whatsapp-tabs"><button className={tab==='connection'?'active':''} onClick={()=>setTab('connection')}><Plug size={14}/> Connection</button><button className={tab==='messages'?'active':''} onClick={()=>setTab('messages')}><MessageCircle size={14}/> Messages & delivery</button></div>{tab==='connection'?<ConnectionPanel gymId={gymId} connection={connection} onRefresh={load} onSaved={async()=>{await load();setSaved('WhatsApp connection saved. Test the connection before sending messages.');setTab('connection')}} onTested={load} onDisconnected={async()=>{await load();setSaved('WhatsApp disconnected.')}} onError={setError}/>:<MessagePanel gymId={gymId} connected={connection?.last_test_ok===true} notifications={notifications} logs={logs} onCompose={()=>setCompose(true)} onRefresh={()=>setLogsRefresh(x=>x+1)} onError={setError}/>} {compose&&<CustomMessage gymId={gymId} onClose={()=>setCompose(false)} onSaved={()=>{setCompose(false);setLogsRefresh(x=>x+1);setSaved('Message queued. Sending happens in the background; check Messages & Delivery for the provider status.')}} onError={setError}/>}</>;
}

function ConnectionPanel({gymId,connection,onRefresh,onSaved,onDisconnected,onError}:{gymId:string;connection:any;onRefresh:()=>Promise<void>;onSaved:()=>void;onDisconnected:()=>void;onError:(x:string)=>void}){
 const[phoneNumberId,setPhoneNumberId]=useState(connection?.phone_number_id||''),[businessId,setBusinessId]=useState(connection?.business_account_id||''),[token,setToken]=useState(''),[version,setVersion]=useState(connection?.api_version||''),[verify,setVerify]=useState(''),[metaAppSecret,setMetaAppSecret]=useState(''),[busy,setBusy]=useState(false),[testing,setTesting]=useState(false),[status,setStatus]=useState('');
 useEffect(()=>{setPhoneNumberId(connection?.phone_number_id||'');setBusinessId(connection?.business_account_id||'');setVersion(connection?.api_version||'')},[connection]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();setStatus('');if(!token.trim()&& !connection?.connected){setStatus('Enter the WhatsApp access token.');return}setBusy(true);try{await saveWhatsappConnection({gymId,businessAccountId:businessId,phoneNumberId,accessToken:token,apiVersion:version,verifyToken:verify,metaAppSecret});setToken('');setVerify('');setMetaAppSecret('');onSaved()}catch(e:any){onError(humanError(e))}finally{setBusy(false)}};
 const test=async()=>{setTesting(true);setStatus('');try{const tokenSession=(await import('../supabase')).getStoredAppSession();const {data,error}=await (await import('../supabase')).supabase!.functions.invoke('test-whatsapp',{body:{},headers:tokenSession?{'x-gym-session':tokenSession}:{}});if(error)throw error;if(data?.error)throw new Error(data.error);setStatus('Connection verified'+(data?.display_phone_number?' · '+data.display_phone_number:'')+(data?.verified_name?' · '+data.verified_name:''));await onTested();}catch(e:any){setStatus(humanError(e))}finally{await onRefresh();setTesting(false)}};
 const disconnect=async()=>{if(!window.confirm('Disconnect WhatsApp for this gym?'))return;try{await disconnectWhatsapp(gymId);onDisconnected()}catch(e:any){onError(humanError(e))}};
 return <Panel title="WhatsApp Business connection" extra={connection?.last_test_ok===true?<span className="connected-badge"><CheckCircle2 size={13}/> Verified</span>:connection?.connected?<span className="disconnected-badge"><AlertCircle size={13}/> Connected · test required</span>:<span className="disconnected-badge"><AlertCircle size={13}/> Not connected</span>}><form className="form" onSubmit={save}><div className="info-card"><b>Enter the Meta WhatsApp Cloud API details</b><span>The access token is stored server-side and is never returned to the browser after saving.</span></div><div className="form-grid"><Field label="WhatsApp Business Account ID"><input value={businessId} onChange={e=>setBusinessId(e.target.value)} placeholder="Optional"/></Field><Field label="Phone Number ID *"><input required value={phoneNumberId} onChange={e=>setPhoneNumberId(e.target.value)}/></Field><Field label={connection?.connected?'New access token (leave blank to keep current)':'Access token *'}><input required={!connection?.connected} type="password" autoComplete="new-password" value={token} onChange={e=>setToken(e.target.value)} placeholder={connection?.connected?'Stored securely':'Paste Meta access token'}/></Field><Field label="Graph API version *"><input required value={version} onChange={e=>setVersion(e.target.value)} placeholder="vXX.X"/></Field><Field label={connection?.connected?'Webhook verify token (leave blank to keep current)':'Webhook verify token *'}><input required={!connection?.connected} value={verify} onChange={e=>setVerify(e.target.value)} placeholder={connection?.connected?'Stored securely':'Set the same token in Meta webhook setup'}/></Field><Field label={connection?.connected?'Meta App Secret (leave blank to keep current)':'Meta App Secret *'}><input required={!connection?.connected} type="password" autoComplete="new-password" value={metaAppSecret} onChange={e=>setMetaAppSecret(e.target.value)} placeholder={connection?.connected?'Stored securely':'Meta app secret'}/></Field></div>{status&&<div className={status.startsWith('Connection verified')?'success-banner':'error-inline'}>{status}</div>}<div className="row-actions"><button className="primary" disabled={busy}>{busy?'Saving…':'Save connection'}</button>{connection?.connected&&<button type="button" className="secondary" disabled={testing} onClick={test}>{testing?'Testing…':'Test connection'}</button>}{connection?.connected&&<button type="button" className="danger-action" onClick={disconnect}><Trash2 size={14}/> Disconnect</button>}</div></form></Panel>
}

function MessagePanel({gymId,connected,notifications,logs,onCompose,onRefresh,onError}:{gymId:string;connected:boolean;notifications:Notification[];logs:any[];onCompose:()=>void;onRefresh:()=>void;onError:(x:string)=>void}){
 return <><Panel title="Custom messaging" extra={<button className="primary small" disabled={!connected} onClick={onCompose}><Send size={14}/> New message</button>}>{!connected?<div className="warning-card">Connect WhatsApp first. Messages cannot be sent until the connection is verified.</div>:<div className="info-card"><b>Background sending enabled</b><span>Messages are queued and sent by the background worker. Do not submit the same message again when this screen is slow. Refresh Messages & Delivery to see queued, sent, delivered, read or failed status.</span></div>}</Panel><Panel title="WhatsApp messages" extra={<button className="icon-button mini" onClick={onRefresh}><RefreshCw size={14}/></button>}>{!notifications.length?<Empty title="No WhatsApp messages" text="Messages created by renewals, reminders or custom messages will appear here."/>:<DataTable rows={notifications.map((n:any)=>({_id:n.id,Member:n.members?.name||'—',Type:n.notification_type,Status:n.status,Delivery:n.delivery_status,Retries:n.retry_count,Sent:n.sent_at||'—',Created:n.created_at,Message:n.message_body||'—',Error:n.error_message||'—'}))}/>}</Panel><Panel title="Delivery logs"><DataTable rows={logs.filter((x:any)=>x.notifications?.channel==='whatsapp').map((l:any)=>({Attempt:l.attempt_at,Member:l.notifications?.members?.name||'—',Status:l.status,Delivery:l.delivery_status||'—',Error:l.error_message||'—'}))}/></Panel></>
}

function CustomMessage({gymId,onClose,onSaved,onError}:{gymId:string;onClose:()=>void;onSaved:()=>void;onError:(x:string)=>void}){
 const[search,setSearch]=useState(''),[members,setMembers]=useState<Member[]>([]),[member,setMember]=useState<Member|null>(null),[body,setBody]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(search.trim().length<2){setMembers([]);return}loadMembers({gymId,page:0,pageSize:8,q:search}).then(r=>setMembers(r.rows)).catch((e:any)=>onError(humanError(e)))},[search,gymId]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!member||!body.trim()||busy)return;setBusy(true);try{await queueNotification({gymId,memberId:member.id,membershipId:null,channel:'whatsapp',type:'manual_message',body:body.trim()});onSaved()}catch(e:any){onError(humanError(e))}finally{setBusy(false)}};
 return <Sheet title="Send custom WhatsApp message" onClose={onClose}><form className="form" onSubmit={submit}>{!member?<><Field label="Find member"><div className="search-box"><MessageCircle size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, mobile or Member ID"/></div></Field>{members.map(m=><button type="button" className="quick-member" key={m.id} onClick={()=>setMember(m)}><div className="avatar">{m.name.slice(0,2).toUpperCase()}</div><div><b>{m.name}</b><span>#{m.member_id} · {m.phone}</span></div></button>)}</>:<><div className="current-membership compact"><div><b>{member.name}</b><span>{member.phone}</span></div><button type="button" className="text-button" onClick={()=>setMember(null)}>Change</button></div><Field label="Message"><textarea required rows={7} value={body} onChange={e=>setBody(e.target.value)} placeholder="Type your custom message"/></Field><button className="primary full" disabled={busy||!body.trim()}>{busy?'Queueing…':'Queue WhatsApp message'}</button></>}</form></Sheet>
}