import React,{useEffect,useState}from'react';
import{MessageCircle,Snowflake}from'lucide-react';
import{cancelMembership,freezeMembership,localDateOffset,loadPackages,loadPaymentMethodSettings,membershipEndByUnit,queueNotification,renewMembership}from'../data';

import type{Member,Package}from'../data';
import{Field,Sheet,StatusTag,Summary,humanError,money}from'./ui';
import{localToday}from'../data';

const METHODS=['cash','upi','card','bank_transfer','cheque','other'];
export function RenewForm({gymId,member,onClose,onSaved}:{gymId:string;member:Member;onClose:()=>void;onSaved:()=>void}){
 const[packages,setPackages]=useState<Package[]>([]),[methods,setMethods]=useState<string[]>(METHODS),[f,setF]=useState<any>({packageId:'',duration:1,price:0,discount:0,paid:0,method:'cash',reference:'',notes:'',start:member.end_date?addDays(member.end_date,1):today()}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{Promise.all([loadPackages(gymId,false),loadPaymentMethodSettings(gymId)]).then(([p,ms])=>{const enabled=ms.filter((m:any)=>m.enabled).map((m:any)=>m.payment_method),first=p[0];setPackages(p);setMethods(enabled);setF((old:any)=>({...old,packageId:old.packageId||first?.id||'',price:old.packageId?old.price:Number(first?.price||old.price||0),duration:old.packageId?old.duration:Number(first?.duration_months||old.duration||1),method:enabled.includes(old.method)?old.method:(enabled[0]||old.method)}))}).catch((x:any)=>setError(humanError(x)))},[gymId]);
 const p=packages.find(x=>x.id===f.packageId),price=p?Number(p.price):Number(f.price||0),duration=p?Number(p.duration_months):Number(f.duration||1),unit=p?.duration_unit||'month',final=Math.max(price-Number(f.discount||0),0),paid=Math.min(Math.max(Number(f.paid||0),0),final),balance=Math.max(final-paid,0),end=membershipEndByUnit(f.start,duration,unit);
 const choose=(pkg:Package)=>setF((old:any)=>({...old,packageId:pkg.id,price:Number(pkg.price),duration:Number(pkg.duration_months),paid:Math.max(0,Number(pkg.price)-Number(old.discount||0))}));
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(!f.start||!end){setError('Select a valid membership duration and start date.');return}if(final>0&&paid<=0){setError('Enter the amount paid for this renewal.');return}if(paid>final){setError('Payment cannot exceed the final membership amount.');return}if(!methods.length&&paid>0){setError('Enable at least one payment method in Settings before renewing.');return}setBusy(true);try{await renewMembership({gymId,memberId:member.id,packageId:f.packageId||null,durationMonths:f.packageId?null:duration,price:f.packageId?null:price,discount:Number(f.discount),amountPaid:paid,paymentMethod:f.method,transactionReference:f.reference||null,notes:f.notes||null,startDate:f.start});onSaved()}catch(x:any){setError(humanError(x))}finally{setBusy(false)}};
 return <Sheet title="Renew membership" onClose={onClose}><form className="form" onSubmit={submit}><div className="info-card"><b>{member.name}</b><span>Current expiry: {member.end_date||'—'}</span></div><div className="package-choice-grid">{packages.map(x=><button type="button" key={x.id} className={f.packageId===x.id?'package-choice selected':'package-choice'} onClick={()=>choose(x)}><b>{x.name}</b><span>{money(x.price)} · {x.duration_months} {x.duration_unit}</span></button>)}</div><div className="form-grid"><Field label="Membership start"><input required type="date" value={f.start} onChange={e=>setF({...f,start:e.target.value})}/></Field><Field label="Membership end"><input type="date" value={end} readOnly aria-readonly="true"/><small className="field-help">Calculated automatically from the selected package or custom duration.</small></Field>{!f.packageId&&<Field label="Custom duration (months)"><input type="number" min="1" value={f.duration} onChange={e=>setF({...f,duration:Number(e.target.value)})}/></Field>}<Field label="Discount"><input type="number" min="0" max={price} value={f.discount} onChange={e=>{const discount=Math.max(Number(e.target.value)||0,0);setF({...f,discount,paid:Math.min(Number(f.paid||0),Math.max(price-discount,0))})}}/></Field><Field label="Amount paid *"><input type="number" min="0" max={final} step="0.01" value={paid} onChange={e=>setF({...f,paid:Number(e.target.value)})}/><small className="field-help">This payment is recorded automatically with the renewal.</small></Field><Field label="Payment method"><select value={f.method} onChange={e=>setF({...f,method:e.target.value})}>{methods.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Transaction reference"><input value={f.reference} onChange={e=>setF({...f,reference:e.target.value})}/></Field></div><div className="calculation"><Summary title="Final membership amount" value={money(final)}/><Summary title="Payment captured" value={money(paid)}/><Summary title="Balance" value={money(balance)}/><Summary title="Membership end" value={end?dateDisplay(end):'—'}/></div><Field label="Notes"><textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></Field>{error&&<div className="error-inline">{error}</div>}<button className="primary full" disabled={busy||!f.packageId&&!Number.isFinite(Number(f.duration))||!end||(!methods.length&&final>0)}>{busy?'Renewing and recording payment…':methods.length?'Renew membership + capture payment':'Enable a payment method first'}</button></form></Sheet>
}
export function FreezeForm({gymId,member,onClose,onSaved}:{gymId:string;member:Member;onClose:()=>void;onSaved:()=>void}){const[s,setS]=useState(today()),[e,setE]=useState(today()),[reason,setReason]=useState('Personal / travel'),[error,setError]=useState('');return <Sheet title="Freeze membership" onClose={onClose}><form className="form" onSubmit={async x=>{x.preventDefault();try{await freezeMembership({gymId,membershipId:member.membership_uuid!,startDate:s,endDate:e,reason});onSaved()}catch(y:any){setError(humanError(y))}}}><div className="info-card"><Snowflake size={17}/><span>Freeze days are added to the membership end date.</span></div><div className="form-grid"><Field label="Start date"><input required type="date" value={s} onChange={x=>setS(x.target.value)}/></Field><Field label="End date"><input required type="date" value={e} onChange={x=>setE(x.target.value)}/></Field></div><Field label="Reason"><input required value={reason} onChange={x=>setReason(x.target.value)}/></Field>{error&&<div className="error-inline">{error}</div>}<button className="primary full" disabled={!member.membership_uuid}>Freeze membership</button></form></Sheet>}
export function CancelForm({gymId,member,onClose,onSaved}:{gymId:string;member:Member;onClose:()=>void;onSaved:()=>void}){const[r,setR]=useState('Member requested cancellation'),[n,setN]=useState(''),[error,setError]=useState('');return <Sheet title="Cancel membership" onClose={onClose}><form className="form" onSubmit={async e=>{e.preventDefault();try{await cancelMembership({gymId,membershipId:member.membership_uuid!,date:today(),reason:r,notes:n});onSaved()}catch(x:any){setError(humanError(x))}}}><div className="warning-card">Historical membership and payment records will be preserved.</div><Field label="Reason"><input required value={r} onChange={e=>setR(e.target.value)}/></Field><Field label="Notes"><textarea value={n} onChange={e=>setN(e.target.value)}/></Field>{error&&<div className="error-inline">{error}</div>}<button className="primary full" disabled={!member.membership_uuid}>Cancel membership</button></form></Sheet>}
export function MessageForm({gymId,member,onClose,onSaved}:{gymId:string;member:Member;onClose:()=>void;onSaved:()=>void}){
 const[b,setB]=useState('Hi '+member.name+', please contact us regarding your gym membership.'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <Sheet title="WhatsApp message" onClose={onClose}><form className="form" onSubmit={async e=>{
  e.preventDefault();if(busy||!b.trim())return;setBusy(true);setError('');
  try{await queueNotification({gymId,memberId:member.id,membershipId:null,channel:'whatsapp',type:'manual_message',body:b.trim()});onSaved()}
  catch(x:any){setError(humanError(x))}
  finally{setBusy(false)}
 }}>
  <div className="info-card"><MessageCircle size={17}/><div><b>{member.phone}</b><span>The message will be sent in the background. Track delivery under WhatsApp → Messages & delivery. Do not submit it again while it is queued.</span></div></div>
  <Field label="Message"><textarea required rows={6} value={b} onChange={e=>setB(e.target.value)}/></Field>
  {error&&<div className="error-inline" role="alert">{error}</div>}
  <button className="primary full" disabled={busy||!b.trim()}><MessageCircle size={16}/>{busy?'Queueing…':'Queue WhatsApp message'}</button>
 </form></Sheet>
}
const today=localToday;const addDays=localDateOffset;const dateDisplay=(value:string)=>new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(value+'T00:00:00'));
