import React,{useEffect,useState}from'react';
import{MessageCircle,Snowflake}from'lucide-react';
import{cancelMembership,freezeMembership,loadPackages,queueNotification,recordPayment,renewMembership}from'../data';
import type{Member,Package}from'../data';
import{Field,Sheet,StatusTag,Summary,humanError,money}from'./ui';
import{localToday}from'../data';

const METHODS=['cash','upi','card','bank_transfer','cheque','other'];
export function RenewForm({gymId,member,onClose,onSaved}:{gymId:string;member:Member;onClose:()=>void;onSaved:()=>void}){
 const[packages,setPackages]=useState<Package[]>([]),[f,setF]=useState<any>({packageId:'',duration:1,price:0,discount:0,paid:0,method:'cash',reference:'',notes:'',start:member.end_date?addDays(member.end_date,1):today(),end:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{loadPackages(gymId,false).then(setPackages).catch(()=>{})},[gymId]);
 const p=packages.find(x=>x.id===f.packageId),price=p?Number(p.price):Number(f.price||0),final=Math.max(price-Number(f.discount||0),0),balance=Math.max(final-Number(f.paid||0),0);
 return <Sheet title="Renew membership" onClose={onClose}><form className="form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await renewMembership({gymId,memberId:member.id,packageId:f.packageId||null,durationMonths:f.packageId?null:Number(f.duration),price:f.packageId?null:price,discount:Number(f.discount),amountPaid:Number(f.paid),paymentMethod:f.method,transactionReference:f.reference||null,notes:f.notes||null,startDate:f.start,endDate:f.end||null});onSaved()}catch(x:any){setError(humanError(x))}finally{setBusy(false)}}}><div className="info-card"><b>{member.name}</b><span>Current expiry: {member.end_date||'—'}</span></div><div className="package-choice-grid">{packages.map(x=><button type="button" key={x.id} className={f.packageId===x.id?'package-choice selected':'package-choice'} onClick={()=>setF({...f,packageId:x.id,price:x.price,duration:x.duration_months})}><b>{x.name}</b><span>{money(x.price)}</span></button>)}</div><div className="form-grid"><Field label="Custom duration"><input type="number" min="1" value={f.duration} onChange={e=>setF({...f,packageId:'',duration:Number(e.target.value)})}/></Field><Field label="Start date"><input type="date" value={f.start} onChange={e=>setF({...f,start:e.target.value})}/></Field><Field label="Manual end date"><input type="date" value={f.end} onChange={e=>setF({...f,end:e.target.value})}/></Field><Field label="Discount"><input type="number" min="0" value={f.discount} onChange={e=>setF({...f,discount:Number(e.target.value)})}/></Field><Field label="Amount paid"><input type="number" min="0" max={final} value={f.paid} onChange={e=>setF({...f,paid:Number(e.target.value)})}/></Field><Field label="Payment method"><select value={f.method} onChange={e=>setF({...f,method:e.target.value})}>{METHODS.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Transaction reference"><input value={f.reference} onChange={e=>setF({...f,reference:e.target.value})}/></Field></div><div className="calculation"><Summary title="Final" value={money(final)}/><Summary title="Paid" value={money(f.paid)}/><Summary title="Balance" value={money(balance)}/></div><Field label="Notes"><textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></Field>{error&&<div className="error-inline">{error}</div>}<button className="primary full" disabled={busy}>{busy?'Renewing…':'Confirm renewal'}</button></form></Sheet>
}
export function FreezeForm({gymId,member,onClose,onSaved}:{gymId:string;member:Member;onClose:()=>void;onSaved:()=>void}){const[s,setS]=useState(today()),[e,setE]=useState(today()),[reason,setReason]=useState('Personal / travel'),[error,setError]=useState('');return <Sheet title="Freeze membership" onClose={onClose}><form className="form" onSubmit={async x=>{x.preventDefault();try{await freezeMembership({gymId,membershipId:member.membership_uuid!,startDate:s,endDate:e,reason});onSaved()}catch(y:any){setError(humanError(y))}}}><div className="info-card"><Snowflake size={17}/><span>Freeze days are added to the membership end date.</span></div><div className="form-grid"><Field label="Start date"><input required type="date" value={s} onChange={x=>setS(x.target.value)}/></Field><Field label="End date"><input required type="date" value={e} onChange={x=>setE(x.target.value)}/></Field></div><Field label="Reason"><input required value={reason} onChange={x=>setReason(x.target.value)}/></Field>{error&&<div className="error-inline">{error}</div>}<button className="primary full" disabled={!member.membership_uuid}>Freeze membership</button></form></Sheet>}
export function CancelForm({gymId,member,onClose,onSaved}:{gymId:string;member:Member;onClose:()=>void;onSaved:()=>void}){const[r,setR]=useState('Member requested cancellation'),[n,setN]=useState(''),[error,setError]=useState('');return <Sheet title="Cancel membership" onClose={onClose}><form className="form" onSubmit={async e=>{e.preventDefault();try{await cancelMembership({gymId,membershipId:member.membership_uuid!,date:today(),reason:r,notes:n});onSaved()}catch(x:any){setError(humanError(x))}}}><div className="warning-card">Historical membership and payment records will be preserved.</div><Field label="Reason"><input required value={r} onChange={e=>setR(e.target.value)}/></Field><Field label="Notes"><textarea value={n} onChange={e=>setN(e.target.value)}/></Field>{error&&<div className="error-inline">{error}</div>}<button className="primary full" disabled={!member.membership_uuid}>Cancel membership</button></form></Sheet>}
export function MessageForm({gymId,member,onClose,onSaved}:{gymId:string;member:Member;onClose:()=>void;onSaved:()=>void}){const[b,setB]=useState('Hi '+member.name+', please contact us regarding your gym membership.'),[error,setError]=useState('');return <Sheet title="WhatsApp message" onClose={onClose}><form className="form" onSubmit={async e=>{e.preventDefault();try{const id=await queueNotification({gymId,memberId:member.id,membershipId:member.membership_uuid,channel:'whatsapp',type:'manual_message',body:b});const f=await import('../data');try{await f.sendWhatsapp(id)}catch{}onSaved()}catch(x:any){setError(humanError(x))}}}><div className="info-card"><MessageCircle size={17}/><span>{member.phone}</span></div><Field label="Message"><textarea rows={6} value={b} onChange={e=>setB(e.target.value)}/></Field>{error&&<div className="error-inline">{error}</div>}<button className="primary full"><MessageCircle size={16}/> Queue & send</button></form></Sheet>}
const today=localToday;const addDays=(s:string,n:number)=>{const d=new Date(s+'T00:00:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
